### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ckanner** [tikv/rust-rocksdb#378]
The machine is MacOs.

My dependency is
`
[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
 package = "rocksdb"
 branch = "tikv-3.0"
`

My cmake version is
`                                                                                                             
cmake version 3.15.5
CMake suite maintained and supported by Kitware (kitware.com/cmake).
`

My gcc version is
`
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

When I run `cargo build`, it build failed, the stderr was showed below
`
--- stderr
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:111:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_BYTES,
    ^
/Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:191:3: note: previous declaration is here
  WAL_FILE_BYTES,   // Number of bytes written to WAL
  ^
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:112:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    WAL_FILE_SYNCED,
    ^
/Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/include/rocksdb/statistics.h:190:3: note: previous declaration is here
  WAL_FILE_SYNCED,  // Number of times WAL sync is done
  ^
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.cc:1:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/base_db_listener.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/titan/src/db_impl.h:3:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/db_impl.h:23:
In file included from /Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/compaction_job.h:24:
/Users/kanner/.cargo/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/81881c1/librocksdb_sys/libtitan_sys/../rocksdb/db/internal_stats.h:113:5: error: declaration shadows a variable in namespace 'rocksdb' [-Werror,-Wshadow]
    BYTES_WRITTEN,
`

How can I resolve it?

**Comment by yiwu-arbug** [comment]
Should be fixed after https://github.com/tikv/rust-rocksdb/pull/376. You can update to the latest master and try again. Please reopen if it doesn't help. Thanks.
