### ISSUE TITLE
Reduce boxing in callback structs

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/rust-rocksdb#513]
RocksDB expose several APIs to allow client code to inject custom logic, such as compaction filter and table properties collector. rust-rocksdb usually implement such APIs in the follow way. 

Assume rocksdb expose such a struct for callback
```
// C++
class Callback {
    virtual void SomeCallback() = 0;
}
```

rust-rocksdb usually provide the API in the following way:
```
// Rust
pub trait Callback {
    fn callback();
}

pub fn new_callback<C: Callback>(callback: C) -> *mut DBCallback {
    let boxed: Box<dyn Callback> = Box::new(callback) as _;
    unsafe {
        crocksdb_ffi::crocksdb_callback_create(
            Box::into_raw(Box::new(boxed)),
            callback_fn,
        )
    }
}

extern "C" fn callback_fn(ctx: *mut c_void) {
    let callback = &*(ctx as *mut Box<dyn Callback>);
    callback.callback();
}
```

Note here `ctx` is a `Box<Box<dyn Callback>>`. The inner box is to hold the trait object. The outer box is needed since C code cannot hold the raw pointer of `Box<dyn Callback>` natively since the pointer is of 128-bits. However, the extra boxing can be reduced by using generic.

```
pub fn new_callback<C: Callback>(callback: C) -> *mut DBCallback {
    let boxed: Box<C> = Box::new(callback);
    unsafe {
        crocksdb_ffi::crocksdb_callback_create(
            Box::into_raw(boxed),
            callback_fn::<C>,
        )
    }
}

extern "C" fn callback_fn<C: Callback>(ctx: *mut c_void) {
    let callback = &*(ctx as *mut C);
    callback.callback();
}
```

The following APIs need to be updated:
* CompactionFilter
* TablePropertiesCollector
* SliceTransform
* EventListener
* Logger
* TableFilter

**Comment by tabokie** [comment]
Reopen this, #663 missed the following types:
- CompationFilter, CompactionFilterFactory
- SliceTransform
