### ISSUE TITLE
Questions:  About IndexType::TwoLevelIndexSearch

### ISSUE THREAD

**Issue by bodhif4** [tikv/rust-rocksdb#523]
What is **TwoLevelIndexSearch**?  I only find two index types (BinarySearch and BinaryAndHash ) in [Rocksdb documentation](https://github.com/facebook/rocksdb/wiki/Data-Block-Hash-Index) but no **TwoLevelIndexSearch**.

**Comment by yiwu-arbug** [comment]
@bodhif4 please see https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters
