### ISSUE TITLE
WriteBatch::iterate memory leak

### ISSUE THREAD

**Issue by yiwu-arbug** [tikv/rust-rocksdb#654]
`WriteBatch::iterate` construct a `Box<WriteBatchCallback>` then convert it into raw pointer and pass it into C code. However, it fail to reclaim the memory. To fix the issue, we need to convert the raw pointer back into `Box<WriteBatchCallback>` and let rust to auto drop it.
https://github.com/tikv/rust-rocksdb/blob/master/src/write_batch.rs#L118

**Comment by yuqi1129** [comment]
Hi, i would like to take this ticket if it has not been assigned

**Comment by tisonkun** [comment]
/assign @yuqi1129 

It is clearly no one be assigned. Thanks for taking over this issue. I'll assign the issue to you.
