### ISSUE TITLE
Doc: update examples

### ISSUE THREAD

**Issue by Nugine** [tikv/rust-rocksdb#685]
https://github.com/tikv/rust-rocksdb/blob/e97c9b50d388ac00aae538afcdbb6224a2b12fda/README.md?plain=1#L86-L90

https://github.com/tikv/rust-rocksdb/blob/e97c9b50d388ac00aae538afcdbb6224a2b12fda/src/rocksdb.rs#L806-L808

Corrected:

```rust
db.write(&batch).unwrap();
```

**Comment by tabokie** [comment]
Thanks for the catch! Could you send us a PR to fix it?
