### ISSUE TITLE
Compile fail in clang 13.1.6 

### ISSUE THREAD

**Issue by waynexia** [tikv/rust-rocksdb#696]
We encounter this compile error while building `rocksdb-rust`: https://github.com/CeresDB/ceresdb/issues/34 (reported by @RayneHwang)

And the workaround is: https://github.com/CeresDB/ceresdb/issues/34#issuecomment-1153698765

It seems to be related to clang's version. We cannot reproduce this under clang 13.0 .

**Comment by tabokie** [comment]
Should be fixed by https://github.com/tikv/titan/pull/231. Please try using a newer version.

**Comment by waynexia** [comment]
Thanks, the master branch looks good ❤️
