### ISSUE TITLE
FFI bindings file generated by bindgen never used actually ?

### ISSUE THREAD

**Issue by guoxiangCN** [tikv/rust-rocksdb#793]
I found that there are two sets of FFI bindings in the project, namely bindings/xx-linux-gnu-binding. rs and src/lib. rs, but there are some differences between the two, so I am a bit confused.

Currently, the binding generated by bindgen is not actually working, is it? If we want to add something, we should still need to manually add the binding in lib.rs, right?

**Comment by Connor1996** [comment]
Yes, the bindgen is never used

**Comment by guoxiangCN** [comment]
Got it , thank you !
